# Generated by Django 6.0.7 on 2026-07-24 03:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='properties/media/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='image', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='properties/thumbnails/')),
                ('blurhash', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Whether the file has been processed (compressed, resized, etc.).')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='properties/covers/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('room_type', models.CharField(choices=[('apartment', 'Apartment'), ('self_contained', 'Self Contained'), ('chamber_and_hall', 'Chamber & Hall'), ('guest_house', 'Guest House')], max_length=30)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('publication_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('bedrooms', models.PositiveSmallIntegerField(default=1)),
                ('bathrooms', models.PositiveSmallIntegerField(default=1)),
                ('toilets', models.PositiveSmallIntegerField(default=1)),
                ('parking_spaces', models.PositiveSmallIntegerField(default=0)),
                ('floor_area', models.DecimalField(blank=True, decimal_places=2, help_text='Area in square metres (m²)', max_digits=8, null=True)),
                ('is_furnished', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='properties', to='home_finder.amenity')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='locations.area')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='locations.district')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
