# Generated by Django 6.0.7 on 2026-07-24 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home_finder', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(limit_choices_to={'role': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='locations.region'),
        ),
        migrations.AddField(
            model_name='property',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='locations.town'),
        ),
        migrations.AddField(
            model_name='propertymedia',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='home_finder.property'),
        ),
    ]
