# Generated by Django 6.0.7 on 2026-07-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_finder', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymedia',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
