# Generated by Django 6.0.7 on 2026-07-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_finder', '0003_propertymedia_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
