# Generated by Django 6.0.7 on 2026-08-06 04:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_finder', '0004_property_views_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandlordDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('national_id', 'National ID / Ghana Card'), ('business_registration', 'Business Registration Certificate'), ('proof_of_address', 'Proof of Address'), ('property_ownership', 'Proof of Property Ownership'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='landlords/documents/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, help_text='For documents with an expiry, e.g. licenses.', null=True)),
                ('landlord', models.ForeignKey(limit_choices_to={'role': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landlord_documents', to='home_finder.property')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Landlord Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
