# Generated by Django 6.0.7 on 2026-08-15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_finder", "0005_landlorddocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyInterest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("property", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="interests", to="home_finder.property")),
                ("tenant", models.ForeignKey(limit_choices_to={"role": "tenant"}, on_delete=django.db.models.deletion.CASCADE, related_name="property_interests", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name_plural": "Property interests", "ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="propertyinterest",
            constraint=models.UniqueConstraint(fields=("property", "tenant"), name="unique_tenant_property_interest"),
        ),
    ]
