# Generated by Django 6.0.7 on 2026-08-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_finder', '0006_propertyinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlorddocument',
            name='document_type',
            field=models.CharField(choices=[('national_id', 'National ID / Ghana Card'), ('property_ownership', 'Proof of Property Ownership'), ('site_plan', 'Site Plan / Indenture'), ('land_title', 'Land Title Certificate / Deed'), ('management_agreement', 'Power of Attorney / Management Agreement'), ('building_permit', 'Building Permit'), ('business_registration', 'Business Registration Certificate'), ('proof_of_address', 'Proof of Address / Utility Bill'), ('other', 'Other Supporting Document')], max_length=40),
        ),
    ]
