# Generated by Django 6.0.7 on 2026-08-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_finder', '0007_alter_landlorddocument_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='payment_period',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
    ]
