# Generated by Django 6.0.7 on 2026-08-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_finder', '0008_alter_property_payment_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
