# Generated by Django 6.0.7 on 2026-09-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_finder', '0009_alter_amenity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='payment_period',
            field=models.CharField(choices=[('daily', 'Daily'), ('hourly', 'Hourly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
    ]
