# Generated by Django 6.0.7 on 2026-08-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyalert',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
