# Generated by Django 6.0.7 on 2026-08-20 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_propertyalert_notified_properties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewingrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='viewingrequest',
            name='guest_email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='viewingrequest',
            name='guest_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='viewingrequest',
            name='guest_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='viewingrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewing_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
