# Generated by Django 6.0.7 on 2026-08-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_landlord_free_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trial_started',
            field=models.BooleanField(default=False, help_text="True once this landlord has been granted a free trial. Stays True forever — even after the trial ends — so the guard, dashboard and emails can distinguish 'never had a trial' from 'trial ran out'."),
        ),
    ]
