# Generated by Django 6.0.7 on 2026-08-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_trial_indexes_and_notification_flag'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_role_tri_end_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_role_notified_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
