"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ
import os


env = environ.Env(
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1', '.railway.app'])

# Fix for CSRF verification failed on deployment domains
# Added wildcard support to ensure all railway deployment subdomains match properly
CSRF_TRUSTED_ORIGINS = env.list(
    'CSRF_TRUSTED_ORIGINS',
    default=['https://homefinder-production-c02a.up.railway.app', 'https://*.railway.app']
)


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'tailwind',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',

    'django.contrib.sites',

    'apps.home_finder',
    'theme',
    'apps.locations',
    'apps.landloards',
    'apps.Subscription',
    'apps.notifications',
    'apps.tenant',
    'apps.chatbot',
    'apps.account.apps.AccountConfig',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.common.context_processors.landlord_subscription_status',
                'apps.landloards.context_processors.landlord_viewing_request_counts',
                'apps.tenant.context_processors.saved_count',
                'apps.tenant.context_processors.recent_saved_properties',
                'apps.tenant.context_processors.tenant_sidebar_counts',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL', default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}")
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': env('REDIS_URL', default='redis://redis:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# ---------------------------------------------------------------------------
# Tailwind CSS (django-tailwind)
# ---------------------------------------------------------------------------
TAILWIND_APP_NAME = 'theme'
NPM_BIN_PATH = env('NPM_BIN_PATH', default='npm')

AUTH_USER_MODEL = 'user_account.User'

AUTHENTICATION_BACKENDS = [
    'apps.account.backends.EmailOrPhoneBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
LOGIN_URL = 'account:login'
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'

# Login & Signup methods
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
SOCIALACCOUNT_AUTO_SIGNUP = True

ACCOUNT_USER_MODEL_USERNAME_FIELD = None


CELERY_BROKER_URL = env(
    "CELERY_BROKER_URL",
    default="redis://127.0.0.1:6379/0",
)

PROPERTY_ALERTS_ENABLED = env.bool("PROPERTY_ALERTS_ENABLED", default=True)
VIEWING_REQUEST_RETENTION_DAYS = env.int("VIEWING_REQUEST_RETENTION_DAYS", default=30)
PROPERTY_ALERTS_REQUIRE_VERIFICATION = env.bool("PROPERTY_ALERTS_REQUIRE_VERIFICATION", default=True)
PROPERTY_ALERTS_FANOUT_MAX_DELAY = env.int("PROPERTY_ALERTS_FANOUT_MAX_DELAY", default=60)

CELERY_RESULT_BACKEND = env(
    "CELERY_RESULT_BACKEND",
    default="redis://127.0.0.1:6379/0",
)

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE


# ---------------------------------------------------------------------------
# Periodic (beat) schedule
# ---------------------------------------------------------------------------
CELERY_BEAT_SCHEDULE = {
    'subscription-expire-and-apply-scheduled-changes': {
        'task': 'Subscription.tasks.expire_and_apply_scheduled_changes',
        'schedule': 24 * 60 * 60,
    },
    'subscription-renewal-reminders': {
        'task': 'Subscription.tasks.send_subscription_renewal_reminders',
        'schedule': 24 * 60 * 60,
    },
    'landlord-trial-expired-notifications': {
        'task': 'Subscription.tasks.expire_landlord_free_trials',
        'schedule': 24 * 60 * 60,
    },
    'landlord-trial-ending-reminders': {
        'task': 'Subscription.tasks.send_trial_ending_reminders',
        'schedule': 24 * 60 * 60,
    },
    'property-alert-catchup': {
        'task': 'tenant.tasks.property_alert_catchup_task',
        'schedule': 60 * 60,
    },
    'purge-stale-viewing-requests': {
        'task': 'tenant.tasks.purge_stale_viewing_requests_task',
        'schedule': 24 * 60 * 60,
    },
}


SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            'client_id': env('GOOGLE_CLIENT_ID', default=''),
            'secret': env('GOOGLE_CLIENT_SECRET', default=''),
            'key': ''
        }
    },
    "facebook": {
        "APP": {
            "client_id": env("FACEBOOK_CLIENT_ID", default=''),
            "secret": env("FACEBOOK_CLIENT_SECRET", default=''),
        }
    },
}

EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = env.int("EMAIL_PORT", default=465)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="erasmuschawey12345@gmail.com")
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=True)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=False)
EMAIL_TIMEOUT = env.int("EMAIL_TIMEOUT", default=20)

PAYSTACK_SECRET_KEY = env("PAYSTACK_SECRET_KEY", default="")
PAYSTACK_PUBLIC_KEY = env("PAYSTACK_PUBLIC_KEY", default="")


FRONTEND_URL = env("FRONTEND_URL", default="http://127.0.0.1:8000")

CHATBOT_AI_PROVIDER = env("OPENAI_API_KEY")