"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ
import os


env = environ.Env(
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'tailwind',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',


    'django.contrib.sites',

    'apps.home_finder',
    'theme',
    'apps.locations',
    'apps.landloards',
    'apps.Subscription',
    'apps.notifications',
    'apps.tenant',
    'apps.account.apps.AccountConfig',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.common.context_processors.landlord_subscription_status',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [ BASE_DIR / 'static']

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': env('REDIS_URL', default='redis://redis:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# ---------------------------------------------------------------------------
# Tailwind CSS (django-tailwind)
# ---------------------------------------------------------------------------
# The standalone top-level "theme" Python package is the Tailwind
# theme app. Its source CSS lives in theme/static_src/src/styles.css
# and the compiled output is written to theme/static/css/dist/styles.css
# (the path django-tailwind hardcodes in its {% tailwind_css %} tag) and
# collected into STATIC_ROOT at deploy time.
TAILWIND_APP_NAME = 'theme'
# `npm` binary used by `python manage.py tailwind build|install|start`.
NPM_BIN_PATH = env('NPM_BIN_PATH', default='npm')

AUTH_USER_MODEL = 'user_account.User'

AUTHENTICATION_BACKENDS = [
    'apps.account.backends.EmailOrPhoneBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_LOGOUT_REDIRECT_URL = '/'

# Login & Signup methods
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
SOCIALACCOUNT_AUTO_SIGNUP = True

ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = True

CELERY_BROKER_URL = env(
    "CELERY_BROKER_URL",
    default="redis://127.0.0.1:6379/0",
)

CELERY_RESULT_BACKEND = env(
    "CELERY_RESULT_BACKEND",
    default="redis://127.0.0.1:6379/0",
)

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# CELERY_TASK_ROUTES = {
#     'tools.process_video': {'queue': 'video_queue'},
#     '*': {'queue': 'celery'},
# }


# ---------------------------------------------------------------------------
# Periodic (beat) schedule
# ---------------------------------------------------------------------------
# All times are in CELERY_TIMEZONE. Add or remove entries here to control
# which background jobs run on a schedule. Tasks themselves remain no-ops
# when there's nothing to do.
CELERY_BEAT_SCHEDULE = {
    # Mark ended subscriptions inactive; apply scheduled downgrades;
    # email landlords whose plans expired with no renewal.
    'subscription-expire-and-apply-scheduled-changes': {
        'task': 'Subscription.tasks.expire_and_apply_scheduled_changes',
        # Run once a day at 02:00 server time.
        'schedule': 24 * 60 * 60,
    },
    # Email landlords N days before their subscription ends (see
    # RENEWAL_REMINDER_DAYS_AHEAD in apps/Subscription/tasks.py).
    'subscription-renewal-reminders': {
        'task': 'Subscription.tasks.send_subscription_renewal_reminders',
        'schedule': 24 * 60 * 60,
    },
    # Notify landlords whose 1-month free trial has ended so they know
    # to subscribe.
    'landlord-trial-expired-notifications': {
        'task': 'Subscription.tasks.expire_landlord_free_trials',
        'schedule': 24 * 60 * 60,
    },
    # Email landlords N days before their free trial ends (see
    # TRIAL_REMINDER_DAYS_AHEAD in apps/Subscription/tasks.py). The
    # critical conversion moment — landlords who get a "your trial
    # ends in 3 days" reminder convert at a much higher rate than
    # those who only see the "trial has ended" email.
    'landlord-trial-ending-reminders': {
        'task': 'Subscription.tasks.send_trial_ending_reminders',
        'schedule': 24 * 60 * 60,
    },
}


SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            'client_id': env('GOOGLE_CLIENT_ID'),
            'secret': env('GOOGLE_CLIENT_SECRET'),
            'key': ''
        }
    },
    "facebook": {
        "APP": {
            "client_id": env("FACEBOOK_CLIENT_ID"),
            "secret": env("FACEBOOK_CLIENT_SECRET"),
            "key": "",
        }
    },
}

EMAIL_BACKEND = env("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="no-reply@homefinder.com")
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=False)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)


PAYSTACK_SECRET_KEY=env("PAYSTACK_SECRET_KEY")
PAYSTACK_PUBLIC_KEY=env("PAYSTACK_PUBLIC_KEY")

FRONTEND_URL = env("FRONTEND_URL")
