# Generated by Django 6.0.7 on 2026-08-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0002_alter_landlordsubscription_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landlordsubscription',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Landlord Subscriptions'},
        ),
        migrations.AddField(
            model_name='landlordsubscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='landlordsubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landlordsubscription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='landlordsubscription',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
