# Generated by Django 6.0.7 on 2026-08-06 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0003_alter_landlordsubscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordsubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text='If True, subscription will not renew and access ends at end_date.'),
        ),
        migrations.AddField(
            model_name='landlordsubscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landlordsubscription',
            name='pending_plan',
            field=models.ForeignKey(blank=True, help_text='Scheduled downgrade target, applied automatically at end_date.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Subscription.subscriptionplan'),
        ),
    ]
